/**
 * Harita Tools - Global State & DOM Element Registry
 */
var state = window.state = {
  flightEngine: null,
  flightMap: null,
  flightOriginalLayer: null,
  flightSimplifiedLayer: null,
  flightRoadLayer: null,
  flightGcpLayer: null,
  flightTriangulationLayer: null,
  isDrawingRoad: false,
  activeRoadPoints: [],
  activeRoadPolyline: null,
  activeRoadMarkers: [],
  isFlightMapInit: false,
  mergerGroups: {},
  currentMergedFiles: {},
  posSolutions: [],
  posText: "",
  csvText: "",
  map: null,
  mapLayerGroup: null,
  cadastreMap: null,
  cadastreLayerGroup: null,
  paftaLayerGroup: null,
  domLayerGroup: null,
  isDomLayerActive: false,
  highlightedPaftaLayer: null,
  activePaftaScale: "off",
  gnssEngine: typeof GnssFormatEngine !== "undefined" ? new GnssFormatEngine() : null,
  rinexEngine: typeof RinexPowerEngine !== "undefined" ? new RinexPowerEngine() : null,
  paftaEngine: typeof PaftaIndexEngine !== "undefined" ? new PaftaIndexEngine() : null,
  tg20Engine: typeof Tg20GeoidEngine !== "undefined" ? new Tg20GeoidEngine() : null,
  tg20Map: null,
  tg20MapMarker: null,
  lastTg20QueryPoint: null,
  converterEngine: typeof UniversalFormatConverterEngine !== "undefined" ? new UniversalFormatConverterEngine() : null,
  converterMap: null,
  converterLayerGroup: null,
  isConverterMapInit: false,
  converterShowLabels: false,
  converterShowTexts: true,
  converterFilterType: "ALL",
  converterSearchQuery: ""
};
var elements = window.elements = {
  navItems: document.querySelectorAll(".nav-item"),
  toolTabs: document.querySelectorAll(".tool-tab"),
  subTabBtns: document.querySelectorAll(".sub-tab-btn"),
  subTabContents: document.querySelectorAll(".subtab-content"),
  pageTitle: document.getElementById("pageTitle"),
  pageSubtitle: document.getElementById("pageSubtitle"),
  globalConsoleLog: document.getElementById("globalConsoleLog"),
  progressBarFill: document.getElementById("progressBarFill"),
  progressLabel: document.getElementById("progressLabel"),
  progressPercent: document.getElementById("progressPercent"),
  btnClearLog: document.getElementById("btnClearLog"),
  btnCopyLog: document.getElementById("btnCopyLog"),
  rw5FileInput: document.getElementById("rw5FileInput"),
  rw5Radius: document.getElementById("rw5Radius"),
  rw5Tolerance: document.getElementById("rw5Tolerance"),
  rw5MinTime: document.getElementById("rw5MinTime"),
  btnAnalyzeRw5: document.getElementById("btnAnalyzeRw5"),
  brandDetectPill: document.getElementById("brandDetectPill"),
  tableGpsFormatRtkBody: document.getElementById("tableGpsFormatRtkBody"),
  tableRw5MatchedBody: document.getElementById("tableRw5MatchedBody"),
  txtCoordOutput: document.getElementById("txtCoordOutput"),
  selectCoordOrder: document.getElementById("selectCoordOrder"),
  btnCopyCoords: document.getElementById("btnCopyCoords"),
  btnDownloadCoordTxt: document.getElementById("btnDownloadCoordTxt"),
  btnFitCadastreMap: document.getElementById("btnFitCadastreMap"),
  btnPrintCadastre: document.getElementById("btnPrintCadastre"),
  btnExportCadastreCsv: document.getElementById("btnExportCadastreCsv"),
  btnExportRtkCsv: document.getElementById("btnExportRtkCsv"),
  btnExportNcn: document.getElementById("btnExportNcn"),
  btnExportKos: document.getElementById("btnExportKos"),
  btnExportDxf: document.getElementById("btnExportDxf"),
  btnExportKmlCadastre: document.getElementById("btnExportKmlCadastre"),
  btnExportTg20RwReport: document.getElementById("btnExportTg20RwReport"),
  barCriterion: document.getElementById("barCriterion"),
  barProj: document.getElementById("barProj"),
  barGeoid: document.getElementById("barGeoid"),
  mergerDropzone: document.getElementById("mergerDropzone"),
  mergerFileInput: document.getElementById("mergerFileInput"),
  mergerResultCard: document.getElementById("mergerResultCard"),
  tableGroupsBody: document.getElementById("tableGroupsBody"),
  btnMergeAll: document.getElementById("btnMergeAll"),
  chkSysGps: document.getElementById("chkSysGps"),
  chkSysGlo: document.getElementById("chkSysGlo"),
  chkSysGal: document.getElementById("chkSysGal"),
  chkSysBds: document.getElementById("chkSysBds"),
  inputExcludeSats: document.getElementById("inputExcludeSats"),
  selectTargetFormat: document.getElementById("selectTargetFormat"),
  selectDecimationStep: document.getElementById("selectDecimationStep"),
  btnExportKml: document.getElementById("btnExportKml"),
  btnExportGeoJson: document.getElementById("btnExportGeoJson"),
  geoLat: document.getElementById("geoLat"),
  geoLon: document.getElementById("geoLon"),
  geoH: document.getElementById("geoH"),
  btnConvertCoord: document.getElementById("btnConvertCoord"),
  coordResultBox: document.getElementById("coordResultBox")
};

window.state = state;
window.elements = elements;
